// Custom worker entry — opennextjs-cloudflare only emits a fetch handler, so
// we wrap it here to attach the scheduled() hook that wrangler's cron trigger
// invokes. See https://opennext.js.org/cloudflare/howtos/custom-worker.

// @ts-expect-error `.open-next/worker.js` is generated by `opennextjs-cloudflare build`.
import { default as handler } from './.open-next/worker.js';
import { runDailyCron } from './lib/cron';

export default {
  fetch: handler.fetch,

  async scheduled(_controller: ScheduledController, env: CloudflareEnv, ctx: ExecutionContext) {
    // waitUntil keeps the isolate alive through the whole prune + backup run;
    // scheduled() itself can return as soon as the work is in flight.
    ctx.waitUntil(runDailyCron(env));
  },
} satisfies ExportedHandler<CloudflareEnv>;
